spring:
  application:
    name: commands

#axon:
#  serializer:
#    general: JACKSON

---
spring:
  profiles: docker-compose
  data:
    mongodb:
      host: mongodb
      port: 27017

server:
  port: 8080

axon:
  axonserver:
    servers: axonserver